name: virtual_learning
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

#export PATH="/Users/amit/Desktop/ITficialProject/FlutterSdk/flutter/bin:$PATH"
#flutter build apk --release --target-platform=android-arm64

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  adobe_xd: ^1.0.0+1
  flutter_svg: ^0.18.1
  flushbar: ^1.10.4
  ionicons: ^0.0.3
  dots_indicator: ^1.2.0
  percent_indicator: ^2.1.7+2
  flutter_swiper: ^1.1.6
  flutter_tindercard: ^0.2.0
  smooth_page_indicator: ^0.2.0
  get: ^3.22.2
  http: ^0.12.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.1
  font_awesome_flutter: ^8.11.0
  flutter_html: ^1.0.0
  youtube_player_flutter: ^7.0.0+7
  flutter_inappwebview: ^4.0.0+4
  flutter_pdfview: ^1.0.1
  permission_handler: 4.4.0
  path_provider: ^1.6.27
  seekbar: ^0.0.2
  cashfree: ^0.1.1
  lottie: ^0.7.0+1
  flutter_windowmanager: ^0.0.2
  youtube_player_iframe: ^1.2.0+2
  app_review: ^2.0.1
  fluttertoast: ^7.1.1
  webview_flutter: ^0.3.21



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons:

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/ic_virtualE_logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/svg/ic_logo_with_tag.svg
     - assets/svg/ic_s.svg
     - assets/svg/ic_slide_01.svg
     - assets/svg/ic_slide_02.svg
     - assets/svg/ic_slide_03.svg
     - assets/svg/ic_back.svg
     - assets/svg/ic_bg_next.svg
     - assets/svg/ic_bg_button.svg
     - assets/svg/
     - assets/images/ic_logo_with_tag.png
     - assets/images/ic_virtualE_logo.png
     - assets/images/ic_test_start.png
     - assets/images/
     - assets/images/ic_top_bg.png
     - assets/images/ic_done.png
     - assets/icons/
     - assets/icons/ic_menu.png
     - assets/subject/economics.svg
     - assets/subject/geometry.svg
     - assets/subject/mathematics.svg
     - assets/subject/physics.svg
     - assets/subject/science.svg
     - assets/subject/chemistry.svg
     - assets/subject/
     - assets/json/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
